//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealership.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheques
    {
        public int idCheque { get; set; }
        public int idCar { get; set; }
        public Nullable<int> idEngine { get; set; }
        public Nullable<int> idColor { get; set; }
        public Nullable<int> idSpoiler { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Engines Engines { get; set; }
        public virtual Spoilers Spoilers { get; set; }
    }
}
